import { defineConfig } from "tsup";

export default defineConfig({
  tsconfig: "./tsconfig.build.json",
  dts: { resolve: false },
  entry: {
    index: "src/index.ts",
    db: "src/db/index.ts",
    "db/schema": "src/db/schema/index.ts",
    ai: "src/ai/index.ts",
    agents: "src/agents/index.ts",
    auth: "src/auth/index.ts",
    repositories: "src/repositories/index.ts",
    errors: "src/errors/index.ts",
    observability: "src/observability/index.ts",
    logging: "src/logging/index.ts",
    audit: "src/audit/index.ts",
    health: "src/health/index.ts",
    telemetry: "src/telemetry/index.ts",
  },
  format: ["esm", "cjs"],
  clean: true,
  sourcemap: true,
  external: [
    "@template/domain",
    "@template/shared",
    "drizzle-orm",
    "better-auth",
    "ai",
    "@ai-sdk/anthropic",
    "@ai-sdk/openai",
    "@ai-sdk/mistral",
    "@langchain/core",
    "@langchain/langgraph",
    "langfuse",
    "pino",
    "pino-pretty",
    "ioredis",
    "postgres",
    "zod",
    "@opentelemetry/api",
    "@opentelemetry/exporter-trace-otlp-http",
    "@opentelemetry/instrumentation-express",
    "@opentelemetry/instrumentation-http",
    "@opentelemetry/instrumentation-pg",
    "@opentelemetry/resources",
    "@opentelemetry/sdk-node",
    "@opentelemetry/sdk-trace-node",
    "@opentelemetry/semantic-conventions",
  ],
});
